// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int runTime = Integer.parseInt(args[0]);
		double small = 0;
		double big = 0;
		for(int i = 0; i < runTime; i ++){
			double x = Math.random();
			if(x > 0.5){
				big += 1.0;
			}else{
				small += 1.0;
			}
		}
		System.out.println("> 0.5: " + big + " times" );
		System.out.println("<= 0.5: " + small + " times" );
		if(big == 0 || small == 0){

		}else{
			double y = (big / small);
			System.out.println("Ratio: "  + y);
		}
	}
}
